# theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
# title: Artemis' Project Portfolio
# description: A home for my projects so I can share them with the world
